language: cpp
sudo: required
os: windows
compiler:
# - gcc
- clang
env:
  - BUILD_TARGET=Debug
  - BUILD_TARGET=Release
  - BUILD_TARGET=RelWithDebInfo
install:
- .travisci/install.sh
script:
- .travisci/build_and_test.sh
cache: ccache
